---
- name: MySQL Role Playbook
  hosts: MySql
  become: yes
  vars_prompt:
    - name: mysql_action
      prompt: "Choose action (install / uninstall / check)"
      private: no
      default: check

    - name: mysql_version
      prompt: "Enter MySQL version (8.0 / 8.1)"
      private: no
      default: "8.0"

  roles:
    - installation_mysql

